spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}

opensearch:
  host: ${OPENSEARCH_HOST}
  port: ${OPENSEARCH_PORT:9200}

aws:
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${S3_BUCKET}
  sqs:
    task-queue-url: ${SQS_TASK_QUEUE_URL}
