apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice-template.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  PLACEHOLDER: {{ "placeholder" | b64enc }}
