apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "microservice-template.fullname" . }}
