FROM eclipse-temurin:11-jre-alpine
RUN addgroup -S spring && adduser -S spring -G spring
WORKDIR /app
COPY api-gateway/target/api-gateway-*.jar app.jar
USER spring
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "app.jar"]
