apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8090
      protocol: TCP
  selector:
    app: {{ include "api-gateway.fullname" . }}
