apiVersion: apps/v1
kind: Deployment
metadata:
  name: devconsole
  labels:
    app: devconsole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devconsole
  template:
    metadata:
      labels:
        app: devconsole
    spec:
      serviceAccountName: devconsole
      containers:
        - name: devconsole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256m -Xmx512m"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /devconsole/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /devconsole/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
