replicaCount: 1

image:
  repository: devconsole
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: 384Mi
    cpu: 100m
  limits:
    memory: 768Mi
    cpu: 500m
