replicaCount: 2

image:
  repository: microservice-template
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  contextPath: /template
  hosts:
    - host: localhost
      paths:
        - path: /template(/|$)(.*)
          pathType: Prefix

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  SPRING_PROFILES_ACTIVE: local

config:
  jwtIssuerUri: ""
  jwtJwkSetUri: ""
